apiVersion: v1
kind: Pod
metadata:
  name: annotationpod
  annotations:
    owner: "Ozgur OZTURK"
    notification-email: "admin@k8sfundamentals.com"
    releasedate: "01.01.2021"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  containers:
  - name: annotationcontainer
    image: nginx
    ports:
    - containerPort: 80


# kubectl apply -f podannotation.yaml
# kubectl apply -f podannotation.yaml

# kubectl annotate pods annotationpod foo=bar       ==> Annotationlar da labellar gibi imperative olarak eklenebiliyor
# kubectl annotate pods annotationpod foo-          ==> Annotationlar da labellar gibi imperative olarak silinebiliyor