apiVersion: v1
kind: Pod
metadata:
  name: crashloopbackpod # containerda bir seylerin yanlis gittigi ve devamli restart edildigi
spec:
  restartPolicy: Always # container in her zaman ayakta olmasini istiyoruz
  containers:
  - name: crashloopbackcontainer
    image: ubuntu:latest
    command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 20']

# kubectl get pods -w 
# kubectl apply -f pod/podlife4.yaml