apiVersion: v1
kind: Pod
metadata:
  name: imageerrorpod
spec:
  containers:
  - name: imageerrorcontainer
    image: enignx # image ismi yanlis yazilmis

# kubectl get pods -w 
# kubectl apply -f pod/podlife1.yaml
