apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376

# bize myservice isimli dns kaydi olusturacak
# kubectl apply -f service1.yaml