apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jr-production-rb
  namespace: production
subjects:
- kind: Group
  name: junior
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

# juniourun production da ise sadece okuma hakkinin olmasini istiyorduk.
# bunun icin juniour isimli grubun production namespacesinde view rolunu atamaktayiz