apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sr-cluster-crb
subjects:
- kind: Group
  name: senior
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

# artik namespace ozelinde istemedigimiz icin cluster genelinde atama yapmaliyiz. 
# seniour groubu cluster in genelinde edit etme hakki rolu olsun