apiVersion: v1
kind: Service
metadata:
  name: frontendlb
spec:
  type: LoadBalancer # cloudservice saglayicilar ile kullanilirsa sonuc verecek service
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


