apiVersion: apps/v1
kind: ReplicaSet # deployment objesinden tek farki buradaki ismi
metadata:
  name: firstrs
  labels:
    app: rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rs
  template:
    metadata:
      labels:
        app: rs
    spec:
      containers:
      - name: nginx
        image: nginx # httpd degisikli yapacak olursa replicaset degisikligi uygulamayacaktir. 

# kubectl get replicaset    ==> tek replicaset
# kubectl set image deployment/firstdeployment nginx=httpd
# kubectl get replicaset    ==> deployment ile tekrar replicaset 
# kubectl rollout undo deployment firstdeployment  ==> eski replicaset ayarlarina gecmektedir.
# kubectl apply -f rs.yaml
# kubectl delete rs firstrs


