apiVersion: v1
kind: Pod
metadata:
  name: hostpath
spec:
  containers:
  - name: hostpathcontainer
    image: ozgurozturknet/k8s:blue
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthcheck
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: directory-vol
      mountPath: /dir1
    - name: dircreate-vol
      mountPath: /cache
    - name: file-vol
      mountPath: /cache/config.json       
  volumes: # hostpath olarak olusturabilecegimiz 3 tur volume var
  - name: directory-vol # container icerisinde var olan bir konumu volume olarak tanimliyoruz
    hostPath:
      path: /tmp # container icerisinde dirone klasorunden erisilebilecek
      type: Directory
  - name: dircreate-vol
    hostPath:
      path: /cache # container icerisinde cash isimli konuma bagliyoruz
      type: DirectoryOrCreate # container icerisinde bu konum varsa kullan yoksa olustur.
  - name: file-vol # ozel bir dosya olarak da mount edebilmekteyiz. varsa kullan yoksa yarat
    hostPath:
      path: /cache/config.json
      type: FileOrCreate

# kubectl apply -f podvolumehostpath.yaml
# kubectl exec -it hosthpath -- bash
