apiVersion: v1
kind: Pod
metadata:
  name: imagesecrettest2
  labels:
    app: imagesecret
spec:
  containers:
  - name: imagesecretcontainer
    image: ozgurozturkregistry.azurecr.io/k8s:latest # eger latest ise default olarak Always olur
    imagePullPolicy: Always # IfNotPresent, Never
    # If the tag is latest, k8s defaults imagePullPolicy to Always. Otherwise k8s defaults imagePullPolicy to IfNotPresent
    # Always ==> makinada olup olmamasina bakmadan her zaman imageyi cekecek
    # Never  ==> hic bir zaman gidip cekmeyecek local de varsa kullanacak
    # IfNotPresent  ==> localde varsa cekmeyecek yoksa cekecek
    ports:
    - containerPort: 80
  imagePullSecrets: # bir onceki file dan farkli olan kisim
  - name: regscrt