apiVersion: v1
kind: Pod
metadata:
  name: imagesecrettest1
  labels:
    app: imagesecret
spec:
  containers:
  - name: imagesecretcontainer
    image: ozgurozturkregistry.azurecr.io/k8s:latest # private repository den olusturmak istiyoruz. Kullanici adi ve sifre ile authenticate olunmasi gerekir
    ports:
    - containerPort: 80

# Bu zamana kadar public image repository den image file cektik.
# Fakat production asamasinda imageler private repository de bulunmaktadir