apiVersion: apps/v1
kind: Deployment
metadata:
  name: rcdeployment
  labels:
    team: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recreate
  strategy: # rollout/rollback islemlerindeki uygulanacak strateji
    type: Recreate # oncelikle tum podlari sil sonra yenilerini olustur. Hardcore migrationda uygulanir. iki surumun birbirini etkileyecegi dusunulerek
    # once eski podlar tamamen silinir sonra yenileri olusturulur. 
  template:
    metadata:
      labels:
        app: recreate
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80

# kubectl apply -f deployrecreate.yaml
# kubectl set image deployment rcdeployment nginx=httpd     ==> eski podlar tamamen silinmeden yenileri olusturulmamaktadir. watch veya -w ile izleyebiliriz.