apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole # role objesi ile neredeyse ayni / sadece 2 fark mevcut / burasi ilk fark
metadata:
  name: secret-reader
rules: 
- apiGroups: [""] 
  resources: ["pods"] 
  verbs: ["get", "watch", "list"] 

  # 2. namespace tanimi girilmemis

# role belirledigimiz namespace icerisinde gecerli olan namespace capinda yetki vermek icin;
# cluster rolde ise belirlenen yetkiler tum cluster capinda gecerlidir.

