apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  db_server: "db.example.com" # girecegimiz degeleri bu sekilde veya
  database: "mydatabase"
  site.settings: | # site.settings yazarak girebiliriz. Icerisine daha fazla veri girebiliriz. 
    color=blue
    padding:25px
---
apiVersion: v1
kind: Pod # configmap in poda aktarma sekli ayni secret gibi
metadata:
  name: configmappod
spec:
  containers:
  - name: configmapcontainer
    image: ozgurozturknet/k8s:blue
    env:
      - name: DB_SERVER
        valueFrom:
          configMapKeyRef:
            name: myconfigmap
            key: db_server
      - name: DATABASE
        valueFrom:
          configMapKeyRef:
            name: myconfigmap
            key: database
    volumeMounts:
      - name: config-vol
        mountPath: "/config"
        readOnly: true
  volumes:
    - name: config-vol
      configMap:
        name: myconfigmap

# Gizli olmayan verileri anahtar/deger eslenikleri olarak depolamak icin kullanilan bir API nesnesidir.
# Tutulmasi gereken sifre, ssh anahtari gibi gizli bir veri ise secret degilse configmap uygun olacak.
# Her ikiside ETCD de encoded olarak tutulmadigi icin aynidir. 

# Imperative
  # kubectl create configmap myconfigmap--from-literal=background=blue --from-file=a.txt
  # kubectl get configmap

# Declarative
  # kubectl apply -f configmap.yaml
  # kubectl get pods
  # kubectl exec -it configmappod -- bash
    # printenv yazarsak gorebiliriz.
    # ayrica config isimli klasore de atmistik
      # cd config diyere gorebiliriz
    #